channels:
  - conda-forge
dependencies:
  - delta-spark=2.4.0
  - ipykernel
  - ruff
  - pylint
  - mypy
  - pylint
  - ruff
  - openjdk=17
  - pyspark=3.4.1
  - python=3.10
  - pytest
  - pytest-mock
  - pytest-cov
