channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - pyspark==3.4.1
    - delta-spark==2.4.0
  - ipykernel
  - ruff
  - pylint
  - mypy
  - pylint
  - ruff
  - openjdk=17
  - python=3.10
  - pytest
  - pytest-mock
  - pytest-cov
